"""RWA Invariant Class Library - Solidity generators.

Five parametric invariant templates. Each function takes concrete parameters for one target and
emits a deployable Solidity guard as a string (plus metadata). The Guard Compiler
(synthesis/guard_compiler.py) wraps that output into a thin post-condition contract deployed onto
the fork; the trace differ (synthesis/differ.py) pattern-matches an exploit anomaly to one of
these classes.

These are generators, not proofs: a modifier constrains behavior only at the call site it is
attached to - which is exactly what the bypass-resistance tests probe (a guard on deposit() does
not guard depositAndMint()).
"""

from dataclasses import dataclass, field


@dataclass
class InvariantSpec:
    name: str
    class_name: str
    params: dict
    solidity: str
    description: str
    call_site_guard: bool = True   # False for classes checked empirically over time, not at a call site
    coverage_notes: list = field(default_factory=list)


def adapter_conversion_integrity(adapter_addr, router_addr, tolerance_bps=100):
    """Class 1. Value recorded by the Ledger for a deposit must equal tokens_in * oracle price
    within tolerance_bps. Constrains the OUTPUT of the conversion, so an attacker cannot route
    around it by changing HOW the rate is manipulated. Catches Vuln A / Vuln C directly."""
    name = "AdapterConversionIntegrity_%s" % adapter_addr[-6:]
    solidity = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../src/PriceRouter.sol";

/// @notice Generated by invariants/generators.py::adapter_conversion_integrity
/// Adapter %(adapter)s  Router %(router)s  Tolerance %(tol)d bps
contract %(name)sGuard {
    PriceRouter public immutable priceRouter;
    uint256 public constant TOLERANCE_BPS = %(tol)d;

    constructor(PriceRouter _priceRouter) { priceRouter = _priceRouter; }

    error ConversionIntegrityViolation(uint256 expected, uint256 recorded, uint256 deltaBps);

    modifier assertConversionIntegrity(address adapter, uint256 tokensIn, uint256 valueRecorded) {
        _;
        uint256 price = priceRouter.getPrice(adapter).price;
        uint256 expected = (tokensIn * price) / 1e18;
        uint256 delta = valueRecorded > expected ? valueRecorded - expected : expected - valueRecorded;
        uint256 deltaBps = expected == 0 ? 0 : (delta * 10000) / expected;
        if (deltaBps > TOLERANCE_BPS) revert ConversionIntegrityViolation(expected, valueRecorded, deltaBps);
    }
}
""" % {"adapter": adapter_addr, "router": router_addr, "tol": tolerance_bps, "name": name}
    return InvariantSpec(name, "AdapterConversionIntegrity",
                         {"adapter": adapter_addr, "router": router_addr, "tolerance_bps": tolerance_bps},
                         solidity, "Ledger-recorded value must match tokens_in * oracle price within tolerance.")


def accrual_semantic_consistency(profile_id, expected_accrual_type):
    """Class 2. Observed price behavior over time must match the declared accrual type
    (PriceAccrual / Rebase / MintedDividend / FixedNAV). Validated empirically over feed history -
    there is no single call site to attach a post-condition to, since the violation is a pattern
    over time."""
    name = "AccrualSemanticConsistency_%s" % profile_id
    solidity = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Generated by invariants/generators.py::accrual_semantic_consistency
/// Profile %(pid)s  Expected type %(t)s
/// No call-site guard; enforced by invariants/validators.py::validate_accrual_semantic_consistency
/// over feed-update history and the benign corpus.
contract %(name)sNote {
    string public constant PROFILE_ID = "%(pid)s";
    string public constant EXPECTED_ACCRUAL_TYPE = "%(t)s";
}
""" % {"pid": profile_id, "t": expected_accrual_type, "name": name}
    return InvariantSpec(name, "AccrualSemanticConsistency",
                         {"profile_id": profile_id, "expected_accrual_type": expected_accrual_type},
                         solidity, "Observed price behavior over time must match the declared accrual type.",
                         call_site_guard=False)


def cross_chain_supply_conservation(chains, epoch_length, safety_margin_bps=500):
    """Class 3. Per-epoch cross-chain supply release must stay within a collateral-derived budget.
    Built and documented; NOT exercised live on a single-chain fork in 36 hours."""
    name = "CrossChainSupplyConservation"
    solidity = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Generated by invariants/generators.py::cross_chain_supply_conservation
/// Chains %(chains)s  Epoch %(epoch)d blocks  Safety margin %(m)d bps
/// SCOPE: in the library and advisory format, not exercised live (no cross-chain testbed in 36h).
contract %(name)sGuard {
    uint256 public constant EPOCH_LENGTH = %(epoch)d;
    uint256 public constant SAFETY_MARGIN_BPS = %(m)d;

    error SupplyConservationViolation(uint256 released, uint256 budget);

    function epochReleaseBudget(uint256 totalCollateralValue) public pure returns (uint256) {
        return (totalCollateralValue * (10000 - SAFETY_MARGIN_BPS)) / 10000;
    }

    modifier assertSupplyConservation(uint256 releasedThisEpoch, uint256 totalCollateralValue) {
        _;
        uint256 budget = epochReleaseBudget(totalCollateralValue);
        if (releasedThisEpoch > budget) revert SupplyConservationViolation(releasedThisEpoch, budget);
    }
}
""" % {"chains": chains, "epoch": epoch_length, "m": safety_margin_bps, "name": name}
    spec = InvariantSpec(name, "CrossChainSupplyConservation",
                         {"chains": chains, "epoch_length": epoch_length, "safety_margin_bps": safety_margin_bps},
                         solidity, "Per-epoch cross-chain supply release must stay within a collateral-derived budget.")
    spec.coverage_notes = ["Class and validator built; not exercised live (no single-fork cross-chain testbed)."]
    return spec


def oracle_composition_type_safety(price_path, router_addr):
    """Class 4. The composed price must reduce to [USD / collateral_unit]: a static config-time
    type check plus a runtime dimensional-range check. Catches Vuln B (a dropped multiplier lands
    the composed price far outside its plausible band)."""
    name = "OracleCompositionTypeSafety_%s" % "_".join(price_path)
    solidity = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../src/PriceRouter.sol";

/// @notice Generated by invariants/generators.py::oracle_composition_type_safety
/// Declared price path: %(path)s
contract %(name)sGuard {
    PriceRouter public constant priceRouter = PriceRouter(%(router)s);

    error CompositionRangeViolation(uint256 price, uint256 lo, uint256 hi);

    /// @dev A composed price that silently dropped a multiplier (Vuln B) lands outside this band.
    modifier assertCompositionInRange(address adapter, uint256 lo, uint256 hi) {
        _;
        uint256 price = priceRouter.getPrice(adapter).price;
        if (price < lo || price > hi) revert CompositionRangeViolation(price, lo, hi);
    }
}
""" % {"path": " -> ".join(price_path), "router": router_addr, "name": name}
    return InvariantSpec(name, "OracleCompositionTypeSafety",
                         {"price_path": price_path, "router": router_addr},
                         solidity, "Composed price must type-check to USD/collateral_unit and stay in a plausible range.")


def exchange_rate_delta_bound(adapter_addr, max_delta_bps=100, window_blocks=1):
    """Class 5. |rate(t) - rate(t-window)| / rate(t-window) <= max_delta_bps/10000. Checkpoint
    pattern. General-purpose version of Class 1, scoped per adapter and time window. Catches the
    donation signature (Vuln A): the rate cannot jump more than max_delta_bps within the window."""
    name = "ExchangeRateDeltaBound_%s" % adapter_addr[-6:]
    solidity = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../src/GoldAdapter.sol";

/// @notice Generated by invariants/generators.py::exchange_rate_delta_bound
/// Adapter %(adapter)s  Max delta %(bps)d bps  Window %(win)d block(s)
contract %(name)sGuard {
    GoldAdapter public immutable adapter;
    uint256 public constant MAX_DELTA_BPS = %(bps)d;
    uint256 public constant WINDOW_BLOCKS = %(win)d;

    uint256 public checkpointRate;
    uint256 public checkpointBlock;

    constructor(GoldAdapter _adapter) { adapter = _adapter; }

    error ExchangeRateDeltaViolation(uint256 rateBefore, uint256 rateAfter, uint256 deltaBps);

    modifier assertRateDeltaBound() {
        if (checkpointBlock == 0 || block.number >= checkpointBlock + WINDOW_BLOCKS) {
            checkpointRate = adapter.exchangeRate();
            checkpointBlock = block.number;
        }
        uint256 rateBefore = checkpointRate;
        _;
        uint256 rateAfter = adapter.exchangeRate();
        uint256 delta = rateAfter > rateBefore ? rateAfter - rateBefore : rateBefore - rateAfter;
        uint256 deltaBps = rateBefore == 0 ? 0 : (delta * 10000) / rateBefore;
        if (deltaBps > MAX_DELTA_BPS) revert ExchangeRateDeltaViolation(rateBefore, rateAfter, deltaBps);
    }
}
""" % {"adapter": adapter_addr, "bps": max_delta_bps, "win": window_blocks, "name": name}
    return InvariantSpec(name, "ExchangeRateDeltaBound",
                         {"adapter": adapter_addr, "max_delta_bps": max_delta_bps, "window_blocks": window_blocks},
                         solidity, "Per-window exchange-rate delta must stay within max_delta_bps of the checkpoint.")


GENERATORS = {
    "AdapterConversionIntegrity": adapter_conversion_integrity,
    "AccrualSemanticConsistency": accrual_semantic_consistency,
    "CrossChainSupplyConservation": cross_chain_supply_conservation,
    "OracleCompositionTypeSafety": oracle_composition_type_safety,
    "ExchangeRateDeltaBound": exchange_rate_delta_bound,
}
